{
  "Header": {
    "Original": "CVE-2024-6923 (There is a MEDIUM severity vulnerability affecting CPython.  The  emai ...)",
    "ID": "CVE-2024-6923",
    "Description": "(There is a MEDIUM severity vulnerability affecting CPython.  The  emai ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-4354-1 DLA-3980-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-4354-1",
        "DLA-3980-1"
      ]
    },
    {
      "Original": "- python3.13 3.13.0~rc2-1",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "fixed",
      "Version": "3.13.0~rc2-1"
    },
    {
      "Original": "- python3.12 3.12.5-1",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "fixed",
      "Version": "3.12.5-1"
    },
    {
      "Original": "- python3.11 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "removed"
    },
    {
      "Original": "[bookworm] - python3.11 3.11.2-6+deb12u5",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python3.11",
      "Kind": "fixed",
      "Version": "3.11.2-6+deb12u5"
    },
    {
      "Original": "- python3.9 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "removed"
    },
    {
      "Original": "- python2.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "removed"
    },
    {
      "Original": "[bullseye] - python2.7 \u003cignored\u003e (Unsupported in Bullseye, only included to build a few applications)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python2.7",
      "Kind": "ignored",
      "Description": "Unsupported in Bullseye, only included to build a few applications"
    },
    {
      "Original": "- pypy3 7.3.18+dfsg-1",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.18+dfsg-1"
    },
    {
      "Original": "[bookworm] - pypy3 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pypy3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/121650",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/121650"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/122233",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/122233"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0 (v3.13.0rc2)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0 (v3.13.0rc2)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7 (v3.12.5)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7 (v3.12.5)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/f7c0f09e69e950cf3c5ada9dbde93898eb975533 (v3.11.10)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/f7c0f09e69e950cf3c5ada9dbde93898eb975533 (v3.11.10)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/06f28dc236708f72871c64d4bc4b4ea144c50147 (v3.10.15)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/06f28dc236708f72871c64d4bc4b4ea144c50147 (v3.10.15)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/f7be505d137a22528cb0fc004422c0081d5d90e6 (v3.9.20)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/f7be505d137a22528cb0fc004422c0081d5d90e6 (v3.9.20)"
    }
  ]
}