{
  "Header": {
    "Original": "CVE-2025-55557 (A Name Error occurs in pytorch v2.7.0 when a PyTorch model consists of ...)",
    "ID": "CVE-2025-55557",
    "Description": "(A Name Error occurs in pytorch v2.7.0 when a PyTorch model consists of ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed"
    },
    {
      "Original": "[trixie] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "trixie",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bookworm] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/151738",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/151738"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/pull/151931",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/pull/151931"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/commit/0a470dc7c148a6814b01d28094cd45147c6e5187 (v2.8.0-rc1)",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/commit/0a470dc7c148a6814b01d28094cd45147c6e5187 (v2.8.0-rc1)"
    }
  ]
}