{
  "Header": {
    "Original": "CVE-2025-4330 (Allows the extraction filter to be ignored, allowing symlink targets t ...)",
    "ID": "CVE-2025-4330",
    "Description": "(Allows the extraction filter to be ignored, allowing symlink targets t ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.13 3.13.4-1",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "fixed",
      "Version": "3.13.4-1"
    },
    {
      "Original": "- python3.12 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "removed"
    },
    {
      "Original": "- python3.11 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "removed"
    },
    {
      "Original": "[bookworm] - python3.11 \u003cnot-affected\u003e (Vulnerable code didn't get backported to the version in Bookworm)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python3.11",
      "Kind": "not-affected",
      "Description": "Vulnerable code didn't get backported to the version in Bookworm"
    },
    {
      "Original": "- python3.9 \u003cnot-affected\u003e (Vulnerable code got backported to 3.9.17, but dropped from sid with 3.9.13)",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "not-affected",
      "Description": "Vulnerable code got backported to 3.9.17, but dropped from sid with 3.9.13"
    },
    {
      "Original": "- python2.7 \u003cnot-affected\u003e (Vulnerable code introduced in 3.12)",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced in 3.12"
    },
    {
      "Original": "[experimental] - pypy3 7.3.20+dfsg-1",
      "Type": "package",
      "Release": "experimental",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.20+dfsg-1"
    },
    {
      "Original": "- pypy3 7.3.20+dfsg-2",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.20+dfsg-2"
    },
    {
      "Original": "[trixie] - pypy3 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "trixie",
      "Package": "pypy3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bookworm] - pypy3 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pypy3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bullseye] - pypy3 \u003cnot-affected\u003e (Vulnerable code backported down to stdlib-3.9.17; embedding 3.6.9)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "pypy3",
      "Kind": "not-affected",
      "Description": "Vulnerable code backported down to stdlib-3.9.17; embedding 3.6.9"
    },
    {
      "Original": "- jython \u003cnot-affected\u003e (Vulnerable code introduced in 3.12)",
      "Type": "package",
      "Package": "jython",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced in 3.12"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/135034",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/135034"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/135037",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/135037"
    },
    {
      "Original": "NOTE: https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
      "Type": "NOTE",
      "Description": "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a (main)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a (main)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a (3.14)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a (3.14)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01 (v3.13.4)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01 (v3.13.4)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da (v3.12.11)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da (v3.12.11)"
    },
    {
      "Original": "NOTE: Got backported to 3.9 in https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec (v3.9.17)",
      "Type": "NOTE",
      "Description": "Got backported to 3.9 in https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec (v3.9.17)"
    },
    {
      "Original": "NOTE: Got backported to 3.11 in https://github.com/python/cpython/commit/241f2e54a6a2801a1d2022f0fa56309e124866c3 (v3.11.4)",
      "Type": "NOTE",
      "Description": "Got backported to 3.11 in https://github.com/python/cpython/commit/241f2e54a6a2801a1d2022f0fa56309e124866c3 (v3.11.4)"
    }
  ]
}