{
  "Header": {
    "Original": "CVE-2025-12105 (A flaw was found in the asynchronous message queue handling of the lib ...)",
    "ID": "CVE-2025-12105",
    "Description": "(A flaw was found in the asynchronous message queue handling of the lib ...)"
  },
  "Annotations": [
    {
      "Original": "- libsoup3 \u003cunfixed\u003e",
      "Type": "package",
      "Package": "libsoup3",
      "Kind": "unfixed"
    },
    {
      "Original": "- libsoup2.4 \u003cundetermined\u003e",
      "Type": "package",
      "Package": "libsoup2.4",
      "Kind": "undetermined"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/481",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/481"
    },
    {
      "Original": "NOTE: Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/9ba1243a24e442fa5ec44684617a4480027da960",
      "Type": "NOTE",
      "Description": "Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/9ba1243a24e442fa5ec44684617a4480027da960"
    },
    {
      "Original": "TODO: double-check libsoup2.4, looks introduced later when refactoring and introducing run_until_read_done()",
      "Type": "TODO",
      "Description": "double-check libsoup2.4, looks introduced later when refactoring and introducing run_until_read_done()"
    }
  ]
}