{
  "Header": {
    "Original": "CVE-2025-61911 (python-ldap is a lightweight directory access protocol (LDAP) client A ...)",
    "ID": "CVE-2025-61911",
    "Description": "(python-ldap is a lightweight directory access protocol (LDAP) client A ...)"
  },
  "Annotations": [
    {
      "Original": "- python-ldap \u003cunfixed\u003e (bug #1117858)",
      "Type": "package",
      "Package": "python-ldap",
      "Kind": "unfixed",
      "BugNo": 1117858
    },
    {
      "Original": "NOTE: https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r7r6-cc7p-4v5m",
      "Type": "NOTE",
      "Description": "https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r7r6-cc7p-4v5m"
    },
    {
      "Original": "NOTE: https://github.com/python-ldap/python-ldap/commit/3957526fb1852e84b90f423d9fef34c7af25b85a (main)",
      "Type": "NOTE",
      "Description": "https://github.com/python-ldap/python-ldap/commit/3957526fb1852e84b90f423d9fef34c7af25b85a (main)"
    },
    {
      "Original": "NOTE: https://github.com/python-ldap/python-ldap/commit/464fddacd63092d6e01c62a38316a713c30ca98a (python-ldap-3.4.5)",
      "Type": "NOTE",
      "Description": "https://github.com/python-ldap/python-ldap/commit/464fddacd63092d6e01c62a38316a713c30ca98a (python-ldap-3.4.5)"
    }
  ]
}