{
  "Header": {
    "Original": "CVE-2025-55560 (An issue in pytorch v2.7.0 can lead to a Denial of Service (DoS) when  ...)",
    "ID": "CVE-2025-55560",
    "Description": "(An issue in pytorch v2.7.0 can lead to a Denial of Service (DoS) when  ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed"
    },
    {
      "Original": "[trixie] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "trixie",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bookworm] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/151522",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/151522"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/pull/151897",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/pull/151897"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/commit/225742838bcbf4656a90010257062188f7fcae82 (v2.8.0-rc1)",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/commit/225742838bcbf4656a90010257062188f7fcae82 (v2.8.0-rc1)"
    }
  ]
}